### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by apichai-brnp** [mfrachet/rn-native-portals#4]
<unknown>:0: error: no such file or directory: '../node_modules/rn-native-portals/ios/PortalDestination.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by mfrachet** [comment]
As written in the readme, it s not production ready. I have to invest time on it 😔
