### ISSUE TITLE
Pod install fails

### ISSUE THREAD

**Issue by dylancom** [mfrachet/rn-native-portals#6]
When trying to do a pod install in the ios folder, I'm getting the following errors:
`
[!] The 'RNNativePortals' pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute 'homepage'.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.
`

**Comment by yue-f** [comment]
> 尝试在ios文件夹中进行Pod安装时，出现以下错误：
> `[!] The 'RNNativePortals' pod failed to validate due to 1 error: - ERROR | attributes: Missing required attribute 'homepage'. - WARN | source: The version should be included in the Git tag. - WARN | description: The description is equal to the summary.`

I executed pod install and this error also appears. How can I solve this error?
